import 'server-only';
import fs from 'node:fs/promises';
import path from 'node:path';
import type { StorageProvider } from './StorageProvider';

/**
 * Local-disk storage backend (Phase 20). This is the only backend this repo actually implements
 * and verifies - no real object-storage credentials exist anywhere in this environment (see
 * .env.example's `STORAGE_BUCKET`/`STORAGE_ACCESS_KEY_ID`/etc, which are unset and not wired into
 * `env.ts`), so writing an untestable S3 client would be exactly the "claim it works because the
 * code looks right" the brief explicitly forbids. `StorageProvider` exists so a real S3-compatible
 * client can be added later as a second implementation, selected in `index.ts`, without touching
 * `documents.service.ts` or any route.
 *
 * Deliberately NOT suitable for a real multi-instance/serverless production deployment - local
 * disk isn't shared or durable across instances or redeploys. This is documented, not hidden: see
 * PHASE20_FINAL_REPORT.md's File Storage section for the explicit "IMPLEMENTED LOCALLY, REAL
 * PROVIDER NOT VERIFIED, REQUIRES INFRASTRUCTURE for a real deployment" classification.
 *
 * Storage root lives outside `public/` (so nothing here is ever served as a static file by
 * accident) and outside the Next.js build output, at the project root's own `.uploads/`
 * directory - gitignored, created on first write.
 */
const STORAGE_ROOT = path.join(process.cwd(), '.uploads');

function resolveKeyPath(key: string): string {
  // `key` is always generated by documents.service.ts (a UUID with no path separators), never a
  // caller-supplied filename - but resolve-and-verify defensively anyway, so a bug elsewhere in
  // the codebase can never turn into a path-traversal write/read outside STORAGE_ROOT.
  const resolved = path.resolve(STORAGE_ROOT, key);
  if (resolved !== STORAGE_ROOT && !resolved.startsWith(STORAGE_ROOT + path.sep)) {
    throw new Error('Invalid storage key.');
  }
  return resolved;
}

export class LocalDiskStorageProvider implements StorageProvider {
  async store(key: string, data: Buffer): Promise<void> {
    const filePath = resolveKeyPath(key);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, data);
  }

  async retrieve(key: string): Promise<Buffer | null> {
    try {
      return await fs.readFile(resolveKeyPath(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(resolveKeyPath(key), { force: true });
  }
}
