import type { Category, Product, SupplierProfile, Warehouse } from '@/types/catalog';

/** Fictional demo data only (section 65) - no real brand, supplier, or product claims. */

export const demoCategories: Category[] = [
  { id: 'cat-networking', name: 'Networking', slug: 'networking' },
  { id: 'cat-computing', name: 'Computing', slug: 'computing' },
  { id: 'cat-office-furniture', name: 'Office Furniture', slug: 'office-furniture' },
  { id: 'cat-industrial', name: 'Industrial Equipment', slug: 'industrial-equipment' },
  { id: 'cat-office-equipment', name: 'Office Equipment', slug: 'office-equipment' },
];

export const demoWarehouses: Warehouse[] = [
  { id: 'wh-abc-accra', supplierId: 'supplier-abc', name: 'Accra Warehouse', city: 'Accra', isDefault: true },
  { id: 'wh-prime-accra', supplierId: 'supplier-prime', name: 'Accra Warehouse', city: 'Accra', isDefault: true },
  { id: 'wh-aie-accra', supplierId: 'supplier-aie', name: 'Accra Warehouse', city: 'Accra', isDefault: true },
  { id: 'wh-aie-kumasi', supplierId: 'supplier-aie', name: 'Kumasi Warehouse', city: 'Kumasi' },
  { id: 'wh-wae-lagos', supplierId: 'supplier-wae', name: 'Lagos Warehouse', city: 'Lagos', isDefault: true },
];

export const demoSuppliers: SupplierProfile[] = [
  {
    id: 'supplier-abc',
    companyId: 'supplier-company-abc',
    name: 'ABC Technology Solutions',
    slug: 'abc-technology-solutions',
    categories: ['Networking', 'Computing'],
    city: 'Accra',
    country: 'Ghana',
    verification: 'VERIFIED',
    rating: 4.7,
    reviewCount: 132,
    responseTimeHours: 2,
    completedOrders: 861,
    certifications: ['ISO 9001'],
    description: 'Networking and IT hardware distributor serving businesses across Ghana since 2011.',
  },
  {
    id: 'supplier-prime',
    companyId: 'supplier-company-prime',
    name: 'Prime Office Supplies',
    slug: 'prime-office-supplies',
    categories: ['Office Furniture', 'Office Equipment'],
    city: 'Accra',
    country: 'Ghana',
    verification: 'VERIFIED',
    rating: 4.4,
    reviewCount: 98,
    responseTimeHours: 4,
    completedOrders: 512,
    certifications: [],
    description: 'Office furniture, printers, and workplace supplies for growing companies.',
  },
  {
    id: 'supplier-aie',
    companyId: 'supplier-company-aie',
    name: 'Accra Industrial Equipment',
    slug: 'accra-industrial-equipment',
    categories: ['Industrial Equipment'],
    city: 'Accra',
    country: 'Ghana',
    verification: 'PREMIUM_VERIFIED',
    rating: 4.9,
    reviewCount: 76,
    responseTimeHours: 3,
    completedOrders: 304,
    certifications: ['ISO 9001', 'ISO 45001'],
    description: 'Generators, safety equipment, and industrial machinery for construction and manufacturing.',
  },
  {
    id: 'supplier-wae',
    companyId: 'supplier-company-wae',
    name: 'West Africa Electronics',
    slug: 'west-africa-electronics',
    categories: ['Computing', 'Networking'],
    city: 'Lagos',
    country: 'Nigeria',
    verification: 'VERIFIED',
    rating: 4.3,
    reviewCount: 64,
    responseTimeHours: 6,
    completedOrders: 219,
    certifications: [],
    description: 'Regional distributor of servers, power systems, and enterprise electronics.',
  },
];

export const demoProducts: Product[] = [
  {
    id: 'prod-cisco-switch',
    slug: 'cisco-catalyst-switch',
    name: 'Cisco Catalyst Switch',
    brand: 'Cisco',
    sku: 'C9200L-24P',
    supplierId: 'supplier-abc',
    categoryId: 'cat-networking',
    images: ['https://images.pexels.com/photos/2881227/pexels-photo-2881227.jpeg'],
    description: '24-port managed Ethernet switch with PoE+, built for reliable enterprise and campus networks.',
    specifications: [
      { label: 'Ports', value: '24x 1GbE PoE+' },
      { label: 'Power', value: 'PoE+ 370W budget' },
      { label: 'Dimensions', value: '44.5 x 28 x 4.4 cm' },
      { label: 'Warranty', value: '3 years' },
      { label: 'Country of origin', value: 'Vietnam' },
    ],
    currency: 'GHS',
    basePrice: 8450,
    priceTiers: [
      { minQty: 1, maxQty: 4, unitPrice: 8450 },
      { minQty: 5, maxQty: 19, unitPrice: 8100 },
      { minQty: 20, maxQty: 49, unitPrice: 7850 },
      { minQty: 50, unitPrice: 7650 },
    ],
    moq: 5,
    inventory: [{ warehouseId: 'wh-abc-accra', stock: 42, reserved: 6, lowStockThreshold: 10 }],
    rating: 4.8,
    reviewCount: 54,
    createdAt: '2025-11-01T09:00:00Z',
  },
  {
    id: 'prod-hp-probook',
    slug: 'hp-probook-laptop',
    name: 'HP ProBook Laptop',
    brand: 'HP',
    sku: 'HP-PB450-G10',
    supplierId: 'supplier-abc',
    categoryId: 'cat-computing',
    images: ['https://images.pexels.com/photos/10655906/pexels-photo-10655906.jpeg'],
    description: '14" business laptop with Intel Core i5, 16GB RAM, and a 3-year onsite warranty.',
    specifications: [
      { label: 'Processor', value: 'Intel Core i5-1335U' },
      { label: 'Memory', value: '16GB RAM / 512GB SSD' },
      { label: 'Display', value: '14" FHD' },
      { label: 'Warranty', value: '3 years onsite' },
      { label: 'Country of origin', value: 'China' },
    ],
    currency: 'GHS',
    basePrice: 6200,
    priceTiers: [
      { minQty: 1, maxQty: 9, unitPrice: 6200 },
      { minQty: 10, maxQty: 24, unitPrice: 5950 },
      { minQty: 25, unitPrice: 5700 },
    ],
    moq: 3,
    inventory: [{ warehouseId: 'wh-abc-accra', stock: 68, reserved: 12, lowStockThreshold: 15 }],
    rating: 4.5,
    reviewCount: 89,
    createdAt: '2025-10-20T09:00:00Z',
  },
  {
    id: 'prod-dell-poweredge',
    slug: 'dell-poweredge-server',
    name: 'Dell PowerEdge Server',
    brand: 'Dell',
    sku: 'PE-R650-BASE',
    supplierId: 'supplier-wae',
    categoryId: 'cat-computing',
    images: ['https://images.pexels.com/photos/4508751/pexels-photo-4508751.jpeg'],
    description: '1U rack server for demanding virtualization and database workloads.',
    specifications: [
      { label: 'Processor', value: '2x Intel Xeon Silver' },
      { label: 'Memory', value: '64GB RAM (expandable)' },
      { label: 'Storage', value: '4x 2.5" hot-swap bays' },
      { label: 'Warranty', value: '3 years next-business-day' },
      { label: 'Country of origin', value: 'Ireland' },
    ],
    currency: 'GHS',
    basePrice: 42000,
    priceTiers: [
      { minQty: 1, maxQty: 2, unitPrice: 42000 },
      { minQty: 3, maxQty: 5, unitPrice: 40200 },
      { minQty: 6, unitPrice: 38500 },
    ],
    moq: 1,
    inventory: [{ warehouseId: 'wh-wae-lagos', stock: 11, reserved: 2, lowStockThreshold: 3 }],
    rating: 4.9,
    reviewCount: 22,
    createdAt: '2025-09-15T09:00:00Z',
  },
  {
    id: 'prod-cat6-cable',
    slug: 'cat6-network-cable',
    name: 'CAT6 Network Cable',
    brand: 'Generic',
    sku: 'CAT6-305M-BLU',
    supplierId: 'supplier-abc',
    categoryId: 'cat-networking',
    images: ['https://images.pexels.com/photos/415043/pexels-photo-415043.jpeg'],
    description: '305m box of solid-core CAT6 UTP cable for structured cabling installations.',
    specifications: [
      { label: 'Length', value: '305m box' },
      { label: 'Category', value: 'CAT6 UTP' },
      { label: 'Conductor', value: '23AWG solid copper' },
      { label: 'Warranty', value: '1 year' },
      { label: 'Country of origin', value: 'China' },
    ],
    currency: 'GHS',
    basePrice: 950,
    priceTiers: [
      { minQty: 1, maxQty: 9, unitPrice: 950 },
      { minQty: 10, maxQty: 29, unitPrice: 880 },
      { minQty: 30, unitPrice: 820 },
    ],
    moq: 2,
    inventory: [{ warehouseId: 'wh-abc-accra', stock: 156, reserved: 20, lowStockThreshold: 30 }],
    rating: 4.4,
    reviewCount: 41,
    createdAt: '2025-11-10T09:00:00Z',
  },
  {
    id: 'prod-apc-ups',
    slug: 'apc-ups',
    name: 'APC UPS',
    brand: 'APC',
    sku: 'APC-SMT1500',
    supplierId: 'supplier-wae',
    categoryId: 'cat-networking',
    images: ['https://images.pexels.com/photos/37929911/pexels-photo-37929911.jpeg'],
    description: '1500VA line-interactive UPS for servers and network equipment, built for frequent outages.',
    specifications: [
      { label: 'Capacity', value: '1500VA / 1000W' },
      { label: 'Runtime (half load)', value: '~11 minutes' },
      { label: 'Outlets', value: '8x IEC' },
      { label: 'Warranty', value: '2 years' },
      { label: 'Country of origin', value: 'Philippines' },
    ],
    currency: 'GHS',
    basePrice: 3200,
    priceTiers: [
      { minQty: 1, maxQty: 4, unitPrice: 3200 },
      { minQty: 5, maxQty: 14, unitPrice: 3050 },
      { minQty: 15, unitPrice: 2900 },
    ],
    moq: 1,
    inventory: [{ warehouseId: 'wh-wae-lagos', stock: 34, reserved: 4, lowStockThreshold: 8 }],
    rating: 4.6,
    reviewCount: 37,
    createdAt: '2025-10-05T09:00:00Z',
  },
  {
    id: 'prod-office-desk',
    slug: 'office-desk',
    name: 'Office Desk',
    brand: 'Prime Furnish',
    sku: 'PF-DESK-140',
    supplierId: 'supplier-prime',
    categoryId: 'cat-office-furniture',
    images: ['https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg'],
    description: '140cm office desk with cable management, in a durable laminate finish.',
    specifications: [
      { label: 'Dimensions', value: '140 x 70 x 75 cm' },
      { label: 'Material', value: 'Laminate over particleboard' },
      { label: 'Assembly', value: 'Required, tools included' },
      { label: 'Warranty', value: '2 years' },
      { label: 'Country of origin', value: 'Ghana' },
    ],
    currency: 'GHS',
    basePrice: 1450,
    priceTiers: [
      { minQty: 1, maxQty: 9, unitPrice: 1450 },
      { minQty: 10, maxQty: 24, unitPrice: 1350 },
      { minQty: 25, unitPrice: 1250 },
    ],
    moq: 1,
    inventory: [{ warehouseId: 'wh-prime-accra', stock: 76, reserved: 8, lowStockThreshold: 15 }],
    rating: 4.2,
    reviewCount: 63,
    createdAt: '2025-08-22T09:00:00Z',
  },
  {
    id: 'prod-office-chair',
    slug: 'office-chair',
    name: 'Office Chair',
    brand: 'Prime Furnish',
    sku: 'PF-CHAIR-ERG2',
    supplierId: 'supplier-prime',
    categoryId: 'cat-office-furniture',
    images: ['https://images.pexels.com/photos/31236091/pexels-photo-31236091.jpeg'],
    description: 'Ergonomic mesh-back office chair with adjustable lumbar support and armrests.',
    specifications: [
      { label: 'Material', value: 'Mesh back, foam seat' },
      { label: 'Adjustability', value: 'Height, tilt, lumbar, armrests' },
      { label: 'Max load', value: '120kg' },
      { label: 'Warranty', value: '3 years' },
      { label: 'Country of origin', value: 'Ghana' },
    ],
    currency: 'GHS',
    basePrice: 980,
    priceTiers: [
      { minQty: 1, maxQty: 9, unitPrice: 980 },
      { minQty: 10, maxQty: 24, unitPrice: 910 },
      { minQty: 25, unitPrice: 850 },
    ],
    moq: 1,
    inventory: [{ warehouseId: 'wh-prime-accra', stock: 112, reserved: 10, lowStockThreshold: 20 }],
    rating: 4.3,
    reviewCount: 71,
    createdAt: '2025-08-22T09:00:00Z',
  },
  {
    id: 'prod-industrial-generator',
    slug: 'industrial-generator',
    name: 'Industrial Generator',
    brand: 'Cummins',
    sku: 'CUM-GEN-60KVA',
    supplierId: 'supplier-aie',
    categoryId: 'cat-industrial',
    images: ['https://images.pexels.com/photos/32713414/pexels-photo-32713414.jpeg'],
    description: '60kVA diesel generator with automatic transfer switch, for continuous site power.',
    specifications: [
      { label: 'Output', value: '60kVA / 48kW' },
      { label: 'Fuel', value: 'Diesel' },
      { label: 'Enclosure', value: 'Weatherproof, sound-attenuated' },
      { label: 'Warranty', value: '2 years / 2000 hours' },
      { label: 'Country of origin', value: 'United States' },
    ],
    currency: 'GHS',
    basePrice: 185000,
    priceTiers: [
      { minQty: 1, maxQty: 1, unitPrice: 185000 },
      { minQty: 2, unitPrice: 176000 },
    ],
    moq: 1,
    inventory: [
      { warehouseId: 'wh-aie-accra', stock: 6, reserved: 1, lowStockThreshold: 2 },
      { warehouseId: 'wh-aie-kumasi', stock: 3, reserved: 0, lowStockThreshold: 1 },
    ],
    rating: 4.9,
    reviewCount: 18,
    createdAt: '2025-07-30T09:00:00Z',
  },
  {
    id: 'prod-safety-equipment',
    slug: 'safety-equipment-kit',
    name: 'Safety Equipment Kit',
    brand: 'SafeGuard',
    sku: 'SG-KIT-STD',
    supplierId: 'supplier-aie',
    categoryId: 'cat-industrial',
    images: ['https://images.pexels.com/photos/38070/pexels-photo-38070.jpeg'],
    description: 'Standard site safety kit: hard hat, gloves, safety glasses, and hi-vis vest, per worker.',
    specifications: [
      { label: 'Contents', value: 'Helmet, gloves, glasses, hi-vis vest' },
      { label: 'Standard', value: 'EN 397 (helmet)' },
      { label: 'Sizes', value: 'S-XXL' },
      { label: 'Warranty', value: '1 year' },
      { label: 'Country of origin', value: 'Ghana' },
    ],
    currency: 'GHS',
    basePrice: 280,
    priceTiers: [
      { minQty: 1, maxQty: 19, unitPrice: 280 },
      { minQty: 20, maxQty: 99, unitPrice: 250 },
      { minQty: 100, unitPrice: 220 },
    ],
    moq: 10,
    inventory: [{ warehouseId: 'wh-aie-accra', stock: 340, reserved: 40, lowStockThreshold: 50 }],
    rating: 4.5,
    reviewCount: 29,
    createdAt: '2025-09-02T09:00:00Z',
  },
  {
    id: 'prod-printer',
    slug: 'office-printer',
    name: 'Office Printer',
    brand: 'Canon',
    sku: 'CAN-MF275DW',
    supplierId: 'supplier-prime',
    categoryId: 'cat-office-equipment',
    images: ['https://images.pexels.com/photos/4792283/pexels-photo-4792283.jpeg'],
    description: 'Wireless all-in-one laser printer with duplex printing, scan, and fax.',
    specifications: [
      { label: 'Type', value: 'Mono laser, all-in-one' },
      { label: 'Print speed', value: '29 ppm' },
      { label: 'Connectivity', value: 'Wi-Fi, USB, Ethernet' },
      { label: 'Warranty', value: '1 year' },
      { label: 'Country of origin', value: 'Vietnam' },
    ],
    currency: 'GHS',
    basePrice: 2100,
    priceTiers: [
      { minQty: 1, maxQty: 4, unitPrice: 2100 },
      { minQty: 5, maxQty: 14, unitPrice: 1980 },
      { minQty: 15, unitPrice: 1850 },
    ],
    moq: 1,
    inventory: [{ warehouseId: 'wh-prime-accra', stock: 24, reserved: 3, lowStockThreshold: 8 }],
    rating: 4.1,
    reviewCount: 33,
    createdAt: '2025-10-28T09:00:00Z',
  },
];
