import type { Order } from '@/types/orders';

/** Fictional order history for the demo companies (section 65) - backs the buyer dashboard's
 *  spend/open-orders widgets honestly with real (if seeded) records, rather than fabricated
 *  numbers with nothing behind them. A real backend would populate this from actual checkouts
 *  once Phase 4 builds them. */
export const demoOrders: Order[] = [
  {
    id: 'order-10082',
    reference: 'ORD-10082',
    companyId: 'company-acme-gh',
    supplierId: 'supplier-abc',
    supplierName: 'ABC Technology Solutions',
    purchaseOrderId: 'po-2026-00182',
    department: 'IT',
    costCenterId: 'cc-it-001',
    items: [{ id: 'oi-1', productId: 'prod-cisco-switch', productName: 'Cisco Catalyst Switch', quantity: 5, unitPrice: 8100 }],
    subtotal: 40500,
    tax: 5063,
    deliveryFee: 500,
    total: 46063,
    status: 'PROCESSING',
    paymentStatus: 'PAID',
    deliveryLocation: 'Accra Warehouse',
    expectedDeliveryDate: '2026-09-18T00:00:00Z',
    createdAt: '2026-09-08T10:30:00Z',
  },
  {
    id: 'order-10081',
    reference: 'ORD-10081',
    companyId: 'company-acme-gh',
    supplierId: 'supplier-prime',
    supplierName: 'Prime Office Supplies',
    department: 'Administration',
    costCenterId: 'cc-admin-004',
    items: [{ id: 'oi-2', productId: 'prod-office-chair', productName: 'Office Chair', quantity: 10, unitPrice: 910 }],
    subtotal: 9100,
    tax: 1138,
    deliveryFee: 200,
    total: 10438,
    status: 'SHIPPED',
    paymentStatus: 'PAID',
    deliveryLocation: 'Accra Warehouse',
    expectedDeliveryDate: '2026-09-14T00:00:00Z',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'order-10072',
    reference: 'ORD-10072',
    companyId: 'company-acme-gh',
    supplierId: 'supplier-wae',
    supplierName: 'West Africa Electronics',
    department: 'IT',
    costCenterId: 'cc-it-001',
    items: [{ id: 'oi-3', productId: 'prod-apc-ups', productName: 'APC UPS', quantity: 6, unitPrice: 3050 }],
    subtotal: 18300,
    tax: 2288,
    deliveryFee: 400,
    total: 20988,
    status: 'DELIVERED',
    paymentStatus: 'PAID',
    deliveryLocation: 'Accra Warehouse',
    createdAt: '2026-08-22T09:15:00Z',
  },
  {
    id: 'order-10065',
    reference: 'ORD-10065',
    companyId: 'company-acme-gh',
    supplierId: 'supplier-abc',
    supplierName: 'ABC Technology Solutions',
    department: 'IT',
    costCenterId: 'cc-it-001',
    items: [{ id: 'oi-4', productId: 'prod-hp-probook', productName: 'HP ProBook Laptop', quantity: 8, unitPrice: 5950 }],
    subtotal: 47600,
    tax: 5950,
    deliveryFee: 500,
    total: 54050,
    status: 'PARTIALLY_DELIVERED',
    paymentStatus: 'PAID',
    deliveryLocation: 'Accra Warehouse',
    createdAt: '2026-08-11T11:00:00Z',
  },
  {
    id: 'order-10050',
    reference: 'ORD-10050',
    companyId: 'company-acme-gh',
    supplierId: 'supplier-aie',
    supplierName: 'Accra Industrial Equipment',
    department: 'Operations',
    costCenterId: 'cc-ops-002',
    items: [{ id: 'oi-5', productId: 'prod-safety-equipment', productName: 'Safety Equipment Kit', quantity: 50, unitPrice: 250 }],
    subtotal: 12500,
    tax: 1563,
    deliveryFee: 300,
    total: 14363,
    status: 'CANCELLED',
    paymentStatus: 'REFUNDED',
    deliveryLocation: 'Accra Warehouse',
    createdAt: '2026-07-28T09:00:00Z',
  },
];
